spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:file:./test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create